services:
  - type: worker
    name: sms-bot
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/bot.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: UPSTASH_REDIS_REST_URL
        sync: false
      - key: UPSTASH_REDIS_REST_TOKEN
        sync: false
      - key: REDIS_PREFIX
        value: smsbot
      - key: MIN_BATCH
        value: "1"
      - key: MAX_BATCH
        value: "10"
      - key: ADMIN_USER_IDS
        sync: false
      - key: ALLOWED_USER_IDS
        sync: false
